### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Jeremiah-Roise/PineCast#1]
I see you have no LICENSE file for this project. The default is copyright.  I see some GPL-2.0 magnet links and MIT headers.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Jeremiah-Roise** [comment]
Thanks for the suggestion I'll definitely do that.

**Comment by Jeremiah-Roise** [comment]
Finished thanks for letting me know!
[merged pull](https://github.com/Jeremiah-Roise/PineCast/pull/2)
